### ISSUE TITLE
Front-end Messages

### ISSUE THREAD

**Issue by abdulhalim** [pytesNET/snicker#10]
Hello,

Front-end Messages doesn't use translation strings, it uses from PHP file, the administrator should change these strings in the back-end, else all messages show in English.

Regards,
Abdulhalim

**Comment by SamBrishes** [comment]
Hellow,

Do you mean the frontend form stings or the strings returned by AJAX? Theoretically each string should be translated by the respective .json file except these ones which you can adapt on the administration.

**Comment by abdulhalim** [comment]
Hello,

The strings return by AJAX and the Terms filed, I translate all of them in the JSON file, but it doesn't return the strings. unless changing them in the back-end

**Comment by SamBrishes** [comment]
Hellow,

Hmm... okay. I'll check it out.

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait. This issue has been fixed in Version 0.1.2.

Sincerely,
Sam.
