### ISSUE TITLE
Page not found dosen´t work

### ISSUE THREAD

**Issue by sinalco92** [pytesNET/snicker#15]
Hi, 
if I activate the Snicker plugin and load a page that does not exist, the 404 Error page of the web browser will be displayed, not the one from the bludit: `$language->p('No pages found')`
I use bludit 3.8.1 and Snicker 0.1.1
If I deactivate the snicker plugin, the  `$language->p('No pages found')` works.

**Comment by SamBrishes** [comment]
Hellow,

thanks for your bug report. I uploaded a small bugfix, please download and try the current [master branch](https://github.com/pytesNET/snicker/zipball/master).

Thanks.

Sincerely,
Sam.

**Comment by sinalco92** [comment]
Hi, 

now the 404 Error page works, if the snicker plugin is activated. 
But the plugin is not implemented on the webpage (in the html code from the webpage I can also see no snicker plugin), the plugin is activated in the admin menu.

**Comment by SamBrishes** [comment]
Hellow,

oops, sorry that was my fault. I updated the master branch again, now it should work. ^^

Sincerely,
Sam.

**Comment by sinalco92** [comment]
Hi, 

yes now it works!

**Comment by SamBrishes** [comment]
Perfect :D
