### ISSUE TITLE
[improvement] - Captcha not reloaded

### ISSUE THREAD

**Issue by abdulhalim** [pytesNET/snicker#5]
Hello Sam, 
Thank you for your great job, well-done.
The first thing I noticed that the Captcha code does not load on clicks for sometimes the Captcha is difficult to read.

**Comment by SamBrishes** [comment]
Hello,

thanks and also thanks for reporting :D 

I guess a simple reload function should help to "skip" unreadable captchas. But what do you mean with "does not load on clicks"? The captcha itself gets validated with the main button.

Sincerely,
Sam.

**Comment by abdulhalim** [comment]
Hey,

I meant it does not reload unreadable Captcha by clicking on it, yep you are right

Regards,
Abdulhalim

**Comment by Joduai** [comment]
Just tested the 0.1,o version with "use local captcha by gregway" option enabled and:
1. there's no way to refresh the challenge image
2. once a user provide wrong answer, he is going to always get the same error:
`The answer to the Captcha hasn't been passed or is wrong!`

**Comment by SamBrishes** [comment]
Hellow.

Fixed in Version 0.1.1. The Captcha is now reloading if the user clicks on the Captcha image. It also reloads if the captcha is wrong.

Thanks.

Sincerely,
Sam.
