### ISSUE TITLE
Disable Catcha and TaC

### ISSUE THREAD

**Issue by abdulhalim** [pytesNET/snicker#7]
Hello,

I think the Captcha and Terms and Condition are not necessary for logged-in users, it is somehow annoying :-D

**Comment by SamBrishes** [comment]
Hellow,

I guess that us true :D I'll change that. 

Sincerely, 
Sam.

**Comment by SamBrishes** [comment]
Hellow,

The Captcha and Terms Checkbox is now disabled if the user is logged in

Sincerely,
Sam.
